-- TODO: ADD MIGRATIONS WITH SEA-ORM. I HATE SQLX BLYAT
CREATE TABLE seen_posts (
    id SERIAL PRIMARY KEY,
    link TEXT NOT NULL UNIQUE,
    title TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
